services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hyhk/yoen-back:latest
    ports:
      - '8080'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - '6379'
volumes:
  postgres_data: